sculpin_content_types:
    posts:
        enabled: false
    gadgets:
        type: path
        path: _gadgets
        singular_name: gadget
        layout: gadget
        permalink: /gadgets/gadget.:title.html
        enabled: true
        taxonomies: []
